(function(m){m(window,"undefined"===typeof window._acic?{}:window._acic,"undefined"===typeof window._aci_debug?!1:window._aci_debug)})(function(m,e,r){function h(){if(!(this instanceof h))return new h;this.version="0.0.7";this.urlHit="//www.acint.net/hit/";this.urlJump="//www.acint.net/jump/";this.uid="";this.config={dataProvider:"",allowExtLinksTrack:!0,customData:null}}var s=!!r;"object"!==typeof JSON&&(JSON={});"function"!==typeof JSON.stringify&&function(){function a(a){return 10>a?"0"+a:a}function d(a){f.lastIndex=
0;return f.test(a)?'"'+a.replace(f,function(a){var b=g[a];return"string"===typeof b?b:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+a+'"'}function c(a,g){var f,l,e,h,m=b,n,k=g[a];k&&"object"===typeof k&&"function"===typeof k.toJSON&&(k=k.toJSON(a));"function"===typeof p&&(k=p.call(g,a,k));switch(typeof k){case "string":return d(k);case "number":return isFinite(k)?String(k):"null";case "boolean":case "null":return String(k);case "object":if(!k)return"null";b+=q;n=[];if("[object Array]"===
Object.prototype.toString.apply(k)){h=k.length;for(f=0;f<h;f+=1)n[f]=c(f,k)||"null";e=0===n.length?"[]":b?"[\n"+b+n.join(",\n"+b)+"\n"+m+"]":"["+n.join(",")+"]";b=m;return e}if(p&&"object"===typeof p)for(h=p.length,f=0;f<h;f+=1)l=p[f],"string"===typeof l&&(e=c(l,k))&&n.push(d(l)+(b?": ":":")+e);else for(l in k)Object.prototype.hasOwnProperty.call(k,l)&&(e=c(l,k))&&n.push(d(l)+(b?": ":":")+e);e=0===n.length?"{}":b?"{\n"+b+n.join(",\n"+b)+"\n"+m+"}":"{"+n.join(",")+"}";b=m;return e}}"function"!==typeof Date.prototype.toJSON&&
(Date.prototype.toJSON=function(b){return isFinite(this.valueOf())?this.getUTCFullYear()+"-"+a(this.getUTCMonth()+1)+"-"+a(this.getUTCDate())+"T"+a(this.getUTCHours())+":"+a(this.getUTCMinutes())+":"+a(this.getUTCSeconds())+"Z":null},String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(a){return this.valueOf()});var f,b,q,g,p;"function"!==typeof JSON.stringify&&(f=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g,
g={"\b":"\\b","\t":"\\t","\n":"\\n","\f":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"},JSON.stringify=function(a,d,f){var g;q=b="";if("number"===typeof f)for(g=0;g<f;g+=1)q+=" ";else"string"===typeof f&&(q=f);if((p=d)&&"function"!==typeof d&&("object"!==typeof d||"number"!==typeof d.length))throw Error("JSON.stringify");return c("",{"":a})});Object.prototype.toJSONString||(Object.prototype.toJSONString=function(a){return JSON.stringify(this,a)})}();var g={generateUUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var d=16*Math.random()|0;return("x"==a?d:d&3|8).toString(16)}).toLowerCase()},stringTrimLimit:function(a){a=a.replace(/\s+/gmi," ").replace(/^\s+|\s+$/g,"");1E3<a.length&&(a=a.substr(0,1E3));return a},getTimeZoneOffsetIso8601:function(){var a=function(a){return 10>a?"0"+a:a},d=(new Date).getTimezoneOffset();return(0<d?"-":"+")+a(Math.floor(Math.abs(d)/60))+":"+a(Math.abs(d)%60)},isObject:function(a){return"object"===typeof a&&"[object Object]"===Object.prototype.toString.call(a)},isArray:function(a){return"undefined"!==
typeof Array.isArray?Array.isArray(a):"[object Array]"===Object.prototype.toString.call(a)},isEmptyObject:function(a){for(var d in a)return!1;return!0},isString:function(a){return"string"===typeof a||a instanceof String},encodeUriParam:function(a){a=""+a;return encodeURIComponent instanceof Function?encodeURIComponent(a):escape(a)},implodeUriParams:function(a){var d,c=[];for(d in a)a.hasOwnProperty(d)&&c.push(d+"="+a[d]);return c.join("&")},makeRequestUri:function(a,d){return a+"?"+g.implodeUriParams(d)},
makeRequestImage:function(a){(new Image).src=a},addEventListenerCrossBrowser:function(a,d,c){a.addEventListener?a.addEventListener(d,c,!1):a.attachEvent?a.attachEvent("on"+d,c):"function"==typeof a["on"+d]&&(a["on"+d]=c)},addReadOnlyProperty:function(a,d,c){Object.defineProperty(a,d,{value:c,writeable:!1,enumerable:!0,configurable:!1})},fireEventCrossBrowser:function(a,d){var c,f=document;if(f.createEvent){var b=null;switch(d){case "click":case "dblclick":case "mousedown":case "mouseup":case "mouseover":case "mousemove":case "mouseout":case "mouseenter":case "mouseleave":b=
"MouseEvent";break;case "wheel":b="WheelEvent";break;case "load":case "unload":case "abort":case "error":case "select":case "resize":case "scroll":b="UIEvent";break;case "focus":case "focusin":case "focusout":case "blur":b="FocusEvent";break;case "beforeinput":case "input":b="InputEvent";break;case "keydown":case "keyup":b="KeyboardEvent";break;case "compositionstart":case "compositionupdate":case "compositionend":b="CompositionEvent"}try{c=f.createEvent(b)}catch(g){try{c=f.createEvent("HtmlEvents")}catch(l){try{c=
f.createEvent("Event")}catch(p){throw Error("Cannot create event object for specified event: "+d);}}}c.initEvent(d,!0,!1);a.dispatchEvent(c)}else if(f.createEventObject)c=f.createEventObject(),c.eventType=d,a.fireEvent("on"+d,c);else if("function"==typeof a["on"+d])a["on"+d]()},fireSameEventCrosBrowser:function(a,d,c){var f=document,b;if(f.createEvent)try{b=new c.constructor(d,c),a.dispatchEvent(b)}catch(g){b=f.createEvent("MouseEvent"),b.initMouseEvent(c.type,!0,!0,window,0,c.screenX,c.screenY,c.clientX,
c.clientY,c.ctrlKey,c.altKey,c.shiftKey,c.metaKey,c.button,c.relatedTarget||null),a.dispatchEvent(b)}else if(f.createEventObject)b=f.createEventObject(c),b.eventType=d,a.fireEvent("on"+d,b);else if("function"==typeof a["on"+d])a["on"+d]()},bindOnReady:function(a){function d(){f||(f=!0,a())}function c(){if(!f)try{l.doScroll("left"),d()}catch(a){setTimeout(c,10)}}var f=!1,b=window,g=document,l=g.documentElement;if(g.addEventListener)g.addEventListener("DOMContentLoaded",d,!1);else if(g.attachEvent){try{var p=
null!=b.frameElement}catch(u){}l.doScroll&&!p&&c();g.attachEvent("onreadystatechange",function(){"complete"===g.readyState&&d()})}else if(b.addEventListener)b.addEventListener("load",d,!1);else if(b.attachEvent)b.attachEvent("onload",d);else{var e=b.onload;b.onload=function(){e&&e();d()}}}};h.prototype.init=function(){if(!this.isAlreadyLoaded()){var a=this,d,c=document;this.uid=g.generateUUID();this.parseConfig();d=g.makeRequestUri(this.urlHit,this.collectDataOnInit());g.makeRequestImage(d);if(!0===
this.config.allowExtLinksTrack){var f=function(b){var d=window,c=!1,f;b=b||d.event;var e=b.target||b.srcElement,h=e;if(!("tagName"in e&&"a"==e.tagName.toLowerCase())){for(c=e.parentNode;c;){if("tagName"in c&&"a"==c.tagName.toLowerCase()){f=c;break}if("parentNode"in c)c=c.parentNode;else break}if(f)e=f;else return}if("href"in e&&/^(http:|https:|)\/\/.+/.test(e.href)&&!("hostname"in e&&e.hostname===d.location.hostname)){if(b.shiftKey||b.altKey||b.ctrlKey||b.metaKey)c=!0;c=!0;e.hasOwnProperty("_delayClick")?
!1===e.hasOwnProperty("_canSkipDelay")?"preventDefault"in b?b.preventDefault():b.returnValue=!1:(delete e._canSkipDelay,delete e._delayClick):(d=g.makeRequestUri(a.urlJump,a.collectDataOnClick(b,e)),g.makeRequestImage(d),!1===c&&(e._delayClick=!0,setTimeout(function(){e._canSkipDelay=!0;g.fireSameEventCrosBrowser(h,"click",b)},200),"preventDefault"in b?b.preventDefault():b.returnValue=!1))}};"interactive"==c.readyState||"complete"==c.readyState?g.addEventListenerCrossBrowser(c.body,"click",f):g.bindOnReady(function(){g.addEventListenerCrossBrowser(c.body,
"click",f)})}}};h.prototype.isAlreadyLoaded=function(){if("object"==typeof m._acil&&"function"==typeof m._acil.isLoaded)return!0;"undefined"!==typeof Object.defineProperty?(g.addReadOnlyProperty(m,"_acil",{}),g.addReadOnlyProperty(m._acil,"isLoaded",function(){return!0})):m._acil=function(){return{isLoaded:function(){return!0}}}();return!1};h.prototype.parseConfig=function(){if(g.isObject(e)&&!g.isEmptyObject(e)&&(e.hasOwnProperty("dataProvider")&&(this.config.dataProvider=isNaN(parseInt(e.dataProvider,
10))?"":Math.abs(parseInt(e.dataProvider,10))),e.hasOwnProperty("allowExtLinksTrack")&&(this.config.allowExtLinksTrack=!0===e.allowExtLinksTrack),e.hasOwnProperty("customData"))){var a=e.customData;if(!("undefined"===typeof a||null==a||"function"==typeof a||g.isString(a)&&0===a.length||g.isObject(a)&&g.isEmptyObject(a)||g.isArray(a)&&0===a.length)){try{if(g.isObject(a)||g.isArray(a)){if(a=JSON.stringify(a),"{}"===a||"[]"===a)a=null}else g.isString(a)||(a=a.toString(),0===a.length&&(a=null))}catch(d){if(a=
null,!0===r)throw d;}this.config.customData=a}}};h.prototype.dataAddObligatoryParams=function(a){a.v=this.version;a.uid=this.uid;a.dp=this.config.dataProvider;a.tz=g.encodeUriParam(g.getTimeZoneOffsetIso8601());a.nc=Math.random().toString().substr(2,8)};h.prototype.collectDataOnInit=function(){var a=document,d=window,a={r:g.encodeUriParam(a.referrer||""),u:g.encodeUriParam(d.location.href),rs:d.screen.width+"x"+d.screen.height,t:g.encodeUriParam(g.stringTrimLimit(a.title)),oE:+this.config.allowExtLinksTrack};
null!==this.config.customData&&(a.cd=g.encodeUriParam(g.stringTrimLimit(this.config.customData)));this.dataAddObligatoryParams(a);return a};h.prototype.collectDataOnClick=function(a,d){var c=document,f=window,b={vP:"",c:"",r:"",u:"",aT:"",hT:0},e=a.target.ownerDocument||c,c=e.documentElement,e=e.body;b.vP=(f.innerWidth||c.clientWidth||e.clientWidth)+"x"+(f.innerHeight||c.clientHeight||e.clientHeight);null==a.pageX&&null!=a.clientX?b.c=a.clientX+(c&&c.scrollLeft||e&&e.scrollLeft||0)-(c&&c.clientLeft||
e&&e.clientLeft||0)+"x"+(a.clientY+(c&&c.scrollTop||e&&e.scrollTop||0)-(c&&c.clientTop||e&&e.clientTop||0)):null!==a.pageX&&(b.c=a.pageX+"x"+a.pageY);b.r=g.encodeUriParam(f.location.href);b.u=g.encodeUriParam(d.href);var f=d.childNodes,l=0,h=0,m=0;if(1<=f.length){for(c=0;c<f.length;c++)e=f[c],3!==e.nodeType&&1!==e.nodeType||1!==e.nodeType||(h+=1,"tagName"in f[c]&&"img"===f[c].tagName.toLowerCase()&&(l+=1,m=c));1==l&&l==h?b.hT=1:0<h&&(b.hT=2)}switch(b.hT){case 1:b.aT=f[m].getAttribute("alt")||"";break;
case 2:case 0:b.aT=d.innerHTML?d.innerHTML.toString().replace(/<\/?[^>]+>/gmi,""):""}0<b.aT.length&&(b.aT=g.stringTrimLimit(b.aT),""!==b.aT&&(b.aT=/^(\S+(\s|)){1,10}/gmi.exec(b.aT)[0].replace(/^\s+|\s+$/g,"")));b.aT=g.encodeUriParam(b.aT);this.dataAddObligatoryParams(b);return b};try{(new h).init()}catch(t){if(!0===s)throw t;}});
